mainapp/urls.py
from django.urls import path
from .views import MainIndex, PostCreate

app_name = "name"

urlpatterns = [
    path('', MainIndex.as_view(), name='index'),
    path('create/', PostCreate.as_view(), name='create'),
]

pyfull/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('mainapp.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import UserRegister, user_login, user_logout, user_info, user_info_post

app_name = "user"

urlpatterns = [
    path("register/", UserRegister.as_view(), name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('info/', user_info, name='info'),
    path('info/save/', user_info_post, name='info_save')
]

mainapp/models.py
from django.db import models


class Post(models.Model):
    user = models.ForeignKey('user.User', on_delete=models.RESTRICT)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='image', null=True, blank=True)
    added_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        index_together = (
            ('user', 'added_at'),
            ('added_at', )
        )

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError

from pyfull.validators import PhoneValidator

class UserManager(BaseUserManager):
    def __create_user(self, username, password, *args, **kwargs):
        # username = PhoneValidator.clean(username)
        # if not PhoneValidator.validate(username):
        #     raise ValidationError('Phone Number emas')

        user = User(username=username, **kwargs)
        user.set_password(password)
        user.save()

    def create_user(self, *args, **kwargs):
        kwargs.setdefault('is_staff', False)
        kwargs.setdefault('is_superuser', False)

        if kwargs.get('is_staff') or kwargs.get('is_superuser'):
            raise ValidationError('Error')

        return self.__create_user(*args, **kwargs)


    def create_superuser(self, *args, **kwargs):
        kwargs.setdefault('is_staff', True)
        kwargs.setdefault('is_superuser', True)

        if not kwargs.get('is_staff') or not kwargs.get('is_superuser'):
            raise ValidationError('Error')

        return self.__create_user(*args, **kwargs)


class User(AbstractUser):
    objects = UserManager()

    phone = models.CharField(max_length=14, default=None, null=True, unique=True)

user/forms.py
from django import forms
# from pyfull.validators import PhoneValidator
from django.core.validators import MinLengthValidator   # Validatsiya holatini tekshiramiz
from django.contrib.auth.validators import UnicodeUsernameValidator     # Foydalanuvchini ismini tkshiardi
from django.core.exceptions import ValidationError


from .models import User


class RegistrationForms(forms.Form):
    username = forms.CharField(max_length=20, required=True,
                               validators=[UnicodeUsernameValidator()])
    phone = forms.CharField(max_length=14, required=True)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput, required=True,
                               validators=[MinLengthValidator(6)])
    confirm = forms.CharField(max_length=50, widget=forms.PasswordInput, required=True,
                              validators=[MinLengthValidator(6)])

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise ValidationError("Ushbu nom ro'yxatdan o'tgan")
        return self.cleaned_data['username']

    def clean_phone(self):
        phone =self.cleaned_data['phone']
        if User.objects.filter(phone=phone).exists():
            raise ValidationError("Ushbu raqam ro'yxatdan o'tgan")
        return self.cleaned_data['phone']

    def clean_confirm(self):
        if self.cleaned_data['password'] != self.cleaned_data['confirm']:
            raise ValidationError("Parollar bir xil emas")
        return self.cleaned_data['confirm']

class LoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)


class EditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'phone', 'last_name', 'email']

mainapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from django.shortcuts import redirect, reverse
from django.contrib.auth.decorators import permission_required
from django.core.exceptions import PermissionDenied

from .models import Post



class MainIndex(TemplateView):

    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):

        list = Post.objects.order_by("-added_at").all()

        kwargs['list'] = list

        return super().get_context_data(**kwargs)



class PostCreate(CreateView):

    model = Post
    fields = ['subject', 'content', 'image']
    template_name = 'main/post_form.html'
    success_url = '/'

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        request.title = 'Saqlash'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perm('main.add_post'):
            raise PermissionDenied()
        return super().setup(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        super().form_valid(form)
        return redirect('name:index')

user/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_GET

from .forms import RegistrationForms, LoginForm, EditForm
from .models import User

class UserRegister(View):
    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        request.title = "Ro'yxatdan o'tish"


    def get(self, request):
        form = RegistrationForms()
        request.title = "Ro'yxatdan o'tish"

        return render(request, 'user/registration.html', {
            'form': form
        })

    def post(self, request):
        form = RegistrationForms(data=request.POST)
        if form.is_valid():
            data = form.cleaned_data
            del data['confirm']
            user = User(**data)
            user.set_password(data['password'])
            user.save()
            messages.success(request, "Siz muvaffaqiyatli ro'yxatdan o'tdingiz.")
            return redirect('name:index')

        return render(request, 'user/registration.html', {
            'form': form
        })

def user_login(request):
    request.title = "Tizimga kirish"

    form = LoginForm()
    if request.POST:
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                messages.success(request, "Hush kelibsiz!!! {}".format(user.first_name))
                return redirect('name:index')

            form.add_error('password', 'Username va/yoki parol hato ')

    return render(request, 'user/login.html', {
        'form': form
    })

@login_required
def user_logout(request):
    logout(request)
    return redirect('name:index')


@require_GET
@login_required
def user_info(request):
    request.title = "O'zgartirish"
    return render(request, 'user/edit.html', {
        'form': EditForm(instance=request.user)
    })

@require_POST
@login_required
def user_info_post(request):
    form = EditForm(data=request.POST, instance=request.user)
    if form.is_valid():
        form.save()
        messages.success(request, "Muvaffaqiyatli o'zgartirildi")
        return redirect('name:index')

    return render(request, 'user/edit.html', {
        "form": form}
)

mainapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4">
        <div class="container">
            <a class="navbar-brand" href="{% url 'name:index' %}">PyFull</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#id-main-menu  ">
                    <span class="navbar-toggler-icon"></span>
                </button>
            <div class="collapse navbar-collapse" id="id_main_menu">
                <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item active">
                        <a class="nav-link" href="{% url 'user:info' %}">{{ user.username }}</a>
                    </li>
                    {% if perms.main.add_post %}
                 <li class="nav-item active">
                        <a class="nav-link" href="{% url 'name:create' %}">Post qo'shish</a>
                    </li>
                    {% endif %}
                 <li class="nav-item active">
                        <a class="nav-link" href="{% url 'user:logout' %}">Chiqish</a>
                    </li>
                {% else %}
                    <li class="nav-item {% if url_name == 'user:register' %} active {% endif %}">
                        <a class="nav-link"  href="{% url 'user:register' %}">Ro'yxatdan o'tish</a>
                    </li>
                    <li class="nav-item {% if url_name == 'user:login' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'user:login' %}">Tizimga kirish</a>
                    </li>
                {% endif %}
                </ul>
            </div>
        </div>
    </nav>
<div class="container pt-3">
    {% block content %}

    {% endblock content%}
</div>
<script src="{% static 'vendor/jquery-3.6.0.js' %}"></script>
</body>
</html>

mainapp/templates/form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block content %}
    <div class="row">
        <div class="col-lg-6 offset-lg-3">
            <div class="card">
                <div class="card-header">
                    {{ request.title }}
                </div>
                <div class="card-body">
                    <form method="post" action="{% block url %}{% endblock %}">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <br>
                        <button type="submit" class="btn btn-secondary">{% block button %}{% endblock %}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

mainapp/templates/main/index.html
{% extends 'base.html' %}
{% block title %}{% endblock title %}

{% block content %}
    <table class="table table-bordered table-hover table-striped">
        <thead>
            <th>Sarlavhasi</th>
            <th>Qo'shilgan sanasi</th>
            <th>Harakatlar</th>
        </thead>
        <tbody>
        {% for row in list %}
            <tr>
                <td>{{ row.subject }}</td>
                <td>{{ row.added_at }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="3">Birorta ham post topilmadi</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content%}

mainapp/templates/main/post_form.html
{% extends 'form.html' %}

{% block url %}{% url 'name:create' %}{% endblock %}

{% block button %}{{ request.title }}{% endblock %}

user/templates/user/edit.html
{% extends 'form.html' %}

{% block url %}{% url 'user:info' %}{% endblock %}

{% block button %}{{ request.title }}{% endblock %}

user/templates/user/login.html
{% extends 'form.html' %}

{% block url %}{% url 'user:login' %}{% endblock %}

{% block button %}{{ request.title }}{% endblock %}

user/templates/user/registration.html
{% extends 'form.html' %}

{% block url %}{% url 'user:register' %}{% endblock %}

{% block button %}{{ request.title }}{% endblock %}